# -*- coding: utf-8 -*-
"""twitterapilive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yZO4TwPRKxm_Ir4Do2w8WrZDCxZESUUo
"""

from tweepy import Stream
from tweepy import OAuthHandler
from tweepy.streaming import StreamListener 
import json
import sentiment_mod as s

#consumer key, consumer secret, access token, access secret.
ckey="cNodLucrQg7tNrRN569rxa8iB"
csecret="qKDmRTnC3sOiCzAKgFV2h1tfz6YZYZoHuipsHtGyicQQ6KeNV5"
atoken="1196057209504817153-VlVSyo9qPKFuabnK4CUvM4Esk6u52m"
asecret="dmwBpKgOq78txVqbwYDdriyr0umofvN9HGyHJs5uyphQe"

class listener(StreamListener):

    def on_data(self, data):
        all_data = json.loads(data)

        tweet = all_data["text"]
        sentiment_value, confidence=s.sentiment(tweet)
        print((tweet, sentiment_value, confidence))
        if confidence*100>=80:
          output=open("twitter.txt","a")
          output.write(sentiment_value)
          output.write('\n')
          output.close()


        return True

    def on_error(self, status):
        print(status)

auth = OAuthHandler(ckey, csecret)
auth.set_access_token(atoken, asecret)

twitterStream = Stream(auth, listener())
twitterStream.filter(track=["peace"])



